[dbvrsgim]
h="localhost:27017"
d="vrsgim"
u="vrsgim"
p="vrsgim@234."
[dbsession]
h="localhost:27017"
d="session"
u="sssex"
p="@234.sex"
[dbchadmin]
h="localhost:27017"
d="cuahang"
u="cuahang"
p="cuahang1234@"

[RPCname]
aut="localhost:9877"
[config]
domainallow="http://localhost.com,http://duyhf.noip.me,http://localhost:8080"
appname="chadmin"
ServiceUrl="http://localhost:8084/"
