
[RPCname]
img="localhost:7877"
[dbvrsgim]
h="localhost:27017"
d="vrsgim"
u="vrsgim"
p="vrsgim@234."
[dbsession]
h="localhost:27017"
d="vrsgim"
u="vrsgim"
p="vrsgim@234."
[config]
domainallow="localhost.com,f.localhost"
sameurllimit=0
requestlimit=500
maxUploadMB=2
appname="chadmin"
imagefolder="../images/"
hostname="http://f.localhost"
mainserver="http://x.localhost/"
